name: Release plugin on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: git fetch origin master
    - run: npm version ${GITHUB_REF#refs/*/}
    - run: git add .
    - run: git commit -m "Bump version to ${GITHUB_REF#refs/*/}"
    - run: git push origin HEAD:master
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
